In [4]:
import numpy as np
#np.array
data = [1,2,3,4,5]
arr = np.array(data)
print(data)


[1, 2, 3, 4, 5]


In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
x = range(5)
print(x)

range(0, 5)


In [9]:
y = np.arange(5)
print(y)

[0 1 2 3 4]


In [10]:
#벡터화
arr*y

array([ 0,  2,  6, 12, 20])

In [13]:
print(y)
print(arr)

[0 1 2 3 4]
[1 2 3 4 5]


In [12]:
arr*arr

array([ 1,  4,  9, 16, 25])

In [15]:
-(arr*3)

array([ -3,  -6,  -9, -12, -15])

In [20]:
#리스트는 슬라이스 리스트에서 값을 바꿔도 원본 리스트에 변화가 없다
list = [1,2,3]
slice_list = list[0:2]
slice_list
slice_list[1]=20

In [21]:
slice_list

[1, 20]

In [22]:
list

[1, 2, 3]

In [24]:
#베열은 변화가 있다.
arr = np.array(list)
slice_arr = arr[0:2]
slice_arr[1] = 20

slice_arr

In [27]:
arr

array([ 1, 20,  3])

### 실습예제 2
1부터 10까지의 정수를 원소로 가진 배열을 만들고, 4번째부터 6번째 까지의 값을 slice하여 출력해 보시오.

In [38]:
arr = np.arange(1,11)
slice_arr = arr[3:6]
slice_arr

array([4, 5, 6])

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
data = [[1,2,3],[4,5,6],[7,8,9]]
data_arr = np.array(data)
# [헹, 열]
data_arr[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
#전체는 :
data_arr[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
data_arr.dtype

dtype('int32')

In [47]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
#불리안 색인
name = np.array(['kim', 'lee', 'park', 'kim'])
name

array(['kim', 'lee', 'park', 'kim'], 
      dtype='<U4')

In [54]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
name == 'kim'

array([ True, False, False,  True], dtype=bool)

In [57]:
data[name == 'kim']

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [60]:
data[data>5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 실습예제 3
0부터 15까지의 정수를 가진 4*4 배열을 만들고, 7 이하의 정수를 모두 음수로 바꾸어보시오.

In [61]:
array = np.arange(16).reshape(4,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
array[array<=7] = array[array<=7]*-1

In [70]:
array

array([[ 0, -1, -2, -3],
       [-4, -5, -6, -7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
#팬시 색인
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [73]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
data[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [76]:
data[[0]]

array([[0, 1, 2]])

In [79]:
data[[3,2,0,1]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [80]:
#원본은 그대로 남아있음
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다
data[[3,2,1,0]][:,[2,1,0]]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

### 실습예제 4
-5 부터 4 까지의 정수를 원소로 가진 배열을 만들고, True인 원소의 갯수를 출력해보시오.

In [92]:
arr = np.arange(-5,1)
arr

array([-5, -4, -3, -2, -1,  0])

In [93]:
(arr==True).sum()

0

In [94]:
(arr==False).sum()

1

In [96]:
arr>4

array([False, False, False, False, False, False], dtype=bool)

In [97]:
(arr==False).sum()

1

In [103]:
#list sort
y = [2,4,1,5,8,6,7,3,9]

In [104]:
sorted(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [105]:
y

[2, 4, 1, 5, 8, 6, 7, 3, 9]

In [108]:
y.sort()
y
#y의 내용 바뀜

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [110]:
#배열
z = np.array([2,4,1,5,8,6,7,3,9])
type(z)

numpy.ndarray

In [113]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])
t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [115]:
# 열을 기준으로 소팅
t.sort(0)
t

array([[ 2,  4,  1,  3],
       [ 8, 10,  7,  5],
       [ 9, 12, 11,  6]])

In [117]:
# 행에서 소팅
t.sort(1)
t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [118]:
p=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
# 순서를 임의로 바꾸는 방법
q = np.random.permutation(p)
q

array([9, 2, 4, 7, 6, 1, 5, 3, 8])